<?php

declare(strict_types=1);

use Infrangible\ETrusted\Block\Widget\AggregateRating;
use Magento\Framework\View\TemplateEngine\Php;

/**
 * @author      Andreas Knollmann
 * @copyright   2014-2024 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

/** @var Php $this */
/** @var AggregateRating $block */
?>

<div class="etrusted-rating-summary">
    <h3 class="etrusted-rating-summary-label"><?php echo __('Trusted Shops'); ?> <span class="etrusted-rating-summary-count">(<?php echo $block->getCount(); ?>)</span></h3>
    <div class="etrusted-rating-summary-detail">
        <span class="etrusted-rating-summary-value"><?php echo sprintf('%s / %s', $block->getRating(), $block->getMaxRating()); ?></span>
        <span class="etrusted-rating-summary-value-label"><?php echo __('Total Rating'); ?></span>
    </div>
</div>
