<?php

declare(strict_types=1);

use Infrangible\ETrusted\Block\Widget\Reviews\Item\Rating;
use Magento\Framework\View\TemplateEngine\Php;

/**
 * @author      Andreas Knollmann
 * @copyright   2014-2024 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

/** @var Php $this */
/** @var Rating $block */
$rating = $block->getRating();
?>

<div class="rating-summary item">
    <div class="rating-result">
        <?php $percent = ceil($rating / 5 * 100); ?>
        <span style="width:<?php echo $percent; ?>%"></span>
    </div>
</div>
